name: Battle
version: '${project.version}'
main: com.example.battle.Battle
api-version: 1.16
softdepend: [DiscordSRV]
commands:
  battle:
    description: battleのコマンド(battle <start/reload/tp/stop/give(コマンドブロックのみ)>)
    permission: battle.do